### PR TITLE
feat: add traversal paths

### PR DESCRIPTION
**Pull request by alexcg1**
- Add traversal paths
- Update code to use tensors instead of blobs

### CODE REVIEW

**Comment by alexcg1** [comment]
@delgermurun I'm getting test fails - complaining about `pytest` not being found. I didn't touch that part of the functionality so I don't think it's a problem with *my* code specifically
image

**Comment by delgermurun** [comment]
@alexcg1 yes, you're right.
There must be something changed in upstream dependencies. I'll take a look at it.

**Comment by alexcg1** [comment]
Cool cool. Let me know when we can merge. This is blocking my pdf search notebook

**Comment by delgermurun** [comment]
Adding dummy test helped. Let's merge it for now. We need some real tests. Maybe later.

**Pull request merged**
